Feat 1 calendar component
IT2810/it2810-webutvikling-h18-prosjekt-3-47 pull request #14
Opened 2018-10-14 23:20 UTC by S1GGEN

Har laget en fullstendig kalenderopplevelse, hvor man kan se en kalender, gå til nye datoer enten ved å klikke på pilene/datoer i kalenderen, eller bringe opp systemets datovelger. Man kan også klikke for å få kalenderen tilbake til i dag. De fargede prikkene i kalenderen indikerer hvilke datoer som har hendelser. Man kan legge til nye hendelser i kalenderen, og disse vil også lagres til AsyncStorage

## CalendarScreen
En ganske simpel screen som håndterer `navigationOptions` og instansierer `Calendar` 

## Calendar
Viser en kalender med [react-native-calendars](https://github.com/wix/react-native-calendars). Håndterer alt av valgte datoer, og lagring til og fra AsyncStorage. Instansierer `DayView` og `CalendarEntryInput`. Lang-trykk på en dato i kalenderen bringer opp `CalendarEntryInput` slik at du kan lage en ny hendelse på den dagen. Ellers kan man klikke på "Legg til ny hendelse". Da vil `CalendarEntryInput` instansieres med den valgte datoen (`state.selected`), men man kan bringe opp en datovelger for å endre det.

## DayView
Genererer en overskrift med datoen og dagen, samt en liste med eventuelle hendelser på den valgte datoen. 

## CalendarEntryInput
Genererer en popup også for å legge til nye hendelser i kalenderen.
Bruker flere tredjepartskomponenter:

* [react-native-modal](https://github.com/react-native-community/react-native-modal) for popupen, gir mulighet til å kunne sveipe bort, og den fanger trykk på tilbakeknappen på Android.

* [react-native-modal-datetime-picker](https://github.com/mmazzarolo/react-native-modal-datetime-picker) Gir mulighet for å kun måtte programmere én oppførsel for å få inn dato fra datovelgerne på Android og iOS, som er implementert veldig forskjellig. Oppdaget dog litt problemer med at datovelgeren på iOS ikke ville rendre hvis en Modal allerede var åpen, så måtte gjøre litt spesialtilpasninger der. Ville gjerne raffinert disse mer hvis jeg hadde hatt tilgang på en iOS-enhet i mer enn noen få timer.

* [react-native-material-textfield](https://github.com/n4kz/react-native-material-textfield) Denne gir litt finere tekstfelt med overskrifter og errormeldinger osv. Har litt mer funksjonalitet enn det jeg fikk benyttet meg av, men fungerer likevel ganske greit til mitt behov, selv om den ikke viste seg å være like polert som jeg hadde håpet.

### moment.js
Både Calendar og DayView benytter seg av [moment](https://github.com/moment/moment). Moment gjør det veldig greit å formatere datoer, samt å gå frem og tilbake i tid. Moment.js er muterbar av natur, noe som ikke egentlig er ønskelig i en applikasjon som denne. Moment.js er også veldig tregt til tider. Kan være at [date-fns]() hadde vært mer aktuelt hvis jeg skulle ha skrevet om denne, [men det viser seg at date-fns er tregere enn moment på formatering](https://raygun.com/blog/moment-js-vs-date-fns/), så kan være at innsparingen der ikke hadde vært så stor likevel. 

### Constants
Benytter meg av konstanter for farger og litt locale-innstillinger, slik at jeg slipper at disse er definert inni komponentene. Gjør det også da enklere å gjøre endringer uten å måtte endre så mange linjer kode i drøssevis av filer.

<br>
<br>

# Bilder:

![image](https://user-images.githubusercontent.com/12127271/46923328-7e341300-d016-11e8-89cc-b03bce597622.png)

#### Datovelgeren på forsiden:
![image](https://user-images.githubusercontent.com/12127271/46923334-89873e80-d016-11e8-93ee-a4ad85b40140.png)

#### Popup for å lage ny hendelse:
![image](https://user-images.githubusercontent.com/12127271/46923339-9a37b480-d016-11e8-9f03-776de848f9d3.png)

#### Datovelger inni popupen for å legge til ny hendelse
![image](https://user-images.githubusercontent.com/12127271/46923387-39f54280-d017-11e8-8d41-ce8fb254c784.png)
![image](https://user-images.githubusercontent.com/12127271/46923436-e9321980-d017-11e8-999b-54f6208aaad0.png)

### Brukeren får feilmelding hvis den prøver å legge inn noe ugyldig:
![image](https://user-images.githubusercontent.com/12127271/46923462-49c15680-d018-11e8-9dbe-0b1ce92f842c.png)
### Eller ikke fyller ut det påkrevde feltet og så prøver å lagre:
![image](https://user-images.githubusercontent.com/12127271/46923468-5fcf1700-d018-11e8-908a-25f58495f721.png)

2018-10-16 07:07 UTC, oystholl requested changes
Ser stort sett bra ut, bare et par punkter det kan pirkes på:
- Bytte av dato går litt sakte, føles ikke umiddelbart
- Feltet i bunnen, for dato, ukedag og eventuelle hendelser blir litt lite på min skjerm: 

![image](https://user-images.githubusercontent.com/32361044/46997953-78772400-d121-11e8-8660-b4adf5e58dbc.png)

2018-10-16 08:10 UTC, S1GGEN commented
Tror det blir vanskelig å fikse noe særlig på dette nå, mener at det fungerer godt nok som en proof of concept. Gjorde litt testing, og viste seg at det var veldig vanskelig å endre størrelsen på kalenderen. Tror heller ikke jeg får til så veldig mye forbedringer når det kommer til farten på ting, men kan prøve meg frem og se om jeg kan få gjort det hele litt mer "snappy"

2018-10-17 07:21 UTC, S1GGEN commented
Nå har jeg gjort litt ytelsesforbedringer. `shouldComponentUpdate` hindrer komponenten å re-rendre i tilfeller hvor det ikke er nødvendig, så nå blir det veldig mange færre re-renders mellom forskjellige handlinger, og ting skal en del fortere.

2018-10-17 07:55 UTC, oystholl commented
Signifikant forbedring av hastighet for bytte av dag i fokus. Strålende!

2018-10-17 07:55 UTC, oystholl submitted a review, later dismissed

2018-10-17 08:16 UTC, oystholl approved these changes

2018-10-17 08:17 UTC, merged