Feat 16 geolocation
IT2810/it2810-webutvikling-h18-prosjekt-3-47 pull request #18
Opened 2018-10-17 11:54 UTC by JorgenJohansen

Ting skal fungere ganske greit, har ikke lagt til asyncstorage, men det var ikke noe krav om på denne.

2018-10-17 12:58 UTC, S1GGEN requested changes
Kommenteringen av koden er litt manglende. Den gir kanskje mening for noen som allerede kan koden, men den er veldig vag, så det blir veldig vanskelig for andre å sette seg inn i denne koden. 

Mangler også en del semikolon rundt om kring.
Og skal vi committe Oldman til develop uten å bruke ham i dette prosjektet òg, eller skal vi kanskje droppe det nå? Hvis vi ikke skal droppe ham, må vi finne på et kult easter egg hvor han dukker opp i appen.

Ellers veldig bra, denne komponenten er veldig kul (og motiverende)

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;
Disse konstantene her ser ikke ut til å bli brukt noe sted

2018-10-17 12:58 UTC, S1GGEN commented on package.json
> +    "react-native-maps": "*",
Meningen å ikke spesifisere noe versjonsnummer her? Det kan føre til litt rare problemer

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +                    //maxZoomLevel = {16}
Denne kan vel fjernes

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +                    {markersVisited /*Viser fram alle markørene vi har besøkt*/}
Disse navnene bør kanskje endres litt. (f.eks `markersGoals` eller `goalMarkers` og `visitedMarkers` eller noe lignende)

_"Viser fram alle markørene vi har"_ er en veldig lite tydelig kommentar. Bør heller ha "Viser alle ikke-besøkte markører" eller noe i den dur

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +        }
Kanskje vi kan lage en hjelpefunksjon her for å slippe å ha to nesten helt like løkker etter hverandre?

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +    //Funksjon tick kjøres når vi rendrer komponenten
Koden inni `componentDidMount` skjer når komponenten første gang _mountes_, derav navnet. Derfor blir det feil å skrive "når vi rendrer komponenten" her i kommentaren.

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +    //Funksjon som kaller getLocationAsync med checkGoals som parameter
_Hvorfor kaller den checkGoals som parameter?_
Dette må forklares i kommentaren.

Her sender vi jo med den som en callback som skal bli kalt etter suksess.

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +    //Vi hindrer at vi får flere markører fra vår posisjon
Finnes det noen forklaring på hvorfor vi må gjøre dette? Finnes det en kilde vi kanskje kan lenke til som forklarer?

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +    //Finner posisjons ved hjelp av en async funksjon
"ved hjelp av en async funksjon". Her bør vi forklare hvilken funksjon, og at denne kommer fra expo osv. Og toppkommentaren bør også forklare hva som skjer når vi har fått denne posisjonen. 

Hvilke argumenter tar vi inn, og hva er egentlig de forskjellige argumentene (kan gjerne ha type pluss en tekstlig forklaring) Returnerer vi noe? Oppdaterer vi state? Kaller vi en callback? Slike spørsmål bør kodekommentarene svare på

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +    //Sjekker om målene våre er i nærheten
Her bør det nok forklares at vi henter ut fra state

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +    //Lager en motiverende melding til bruker
* Forklare argumentene vi tar inn (type + tekstlig beskrivelse)
* Forklare hva vi returnerer (type + evt. tekstlig beskrivelse)

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +    //Funksjon som returnerer distansen mellom to steder
Flott, kan også ta med at det er euklidsk distanse og at den blir utregnet i grader.

Samt: 
* Forklare argumentene vi tar inn (type + tekstlig beskrivelse)
* Forklare hva vi returnerer (type + evt. tekstlig beskrivelse)

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +    //Funksjoner som sjekker om vi er i nærheten av målet vårt
* Forklare litt mer hva den egentlig gjør. Hva skjer hvis/når vi har funnet ut at vi er i nærheten av målet vårt?
* Forklare argumentene vi tar inn (type + tekstlig beskrivelse)

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +    //Funksjon som lager en oppdatert liste med hva vi har besøkt
Trenger bedre forklaring. Denne funksjonen tar inn et array og returnerer samme array, bare uten `removeElement` (hvis `removeElement` finnes i arrayet da)

* Forklare argumentene vi tar inn (type + tekstlig beskrivelse)
* Forklare hva vi returnerer (type + evt. tekstlig beskrivelse)

2018-10-17 12:58 UTC, S1GGEN commented on components/Geolocation.js
> +import React, {Component} from 'react';
Kan gjerne ha en kommentar helt på toppen som overordnet forklarer hva som skjer i denne komponenten. At den viser kart og henter inn posisjon. Forklare om de forskjellige markørene og at man kan besøke punkter og få poeng og alt sånt

2018-10-17 12:58 UTC, S1GGEN commented on screens/GeolocationScreen.js
> +    title: 'app.json',
Tittelen her må endres, `app.json` er ikke en veldig fin tittel
![image](https://user-images.githubusercontent.com/12127271/47087165-9e80ef00-d21b-11e8-8693-a75a277b76a7.png)

2018-10-18 10:26 UTC, JorgenJohansen commented on components/Geolocation.js
> +const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;
De er i bruk nå, har satt begge til 0.05 og da kan vi endre dette senere uten å påvirke resten av koden vår.

2018-10-18 10:26 UTC, JorgenJohansen commented on package.json
> +    "react-native-maps": "*",
Har endret til versjonnummer "^0.22.0", og det fungerer godt.

2018-10-18 10:28 UTC, JorgenJohansen commented on components/Geolocation.js
> +                    //maxZoomLevel = {16}
Jepp, dette løses vell med latitudeDelta og longitudeDelta?

2018-10-18 10:33 UTC, JorgenJohansen commented on components/Geolocation.js
> +                    {markersVisited /*Viser fram alle markørene vi har besøkt*/}
Da har jeg gjort om markers til goalMarkers og markersVisited til visitedMarkers, samt skrevet om kommentaren "Viser fram alle markørene vi har" til "Viser fram alle markørene vi ikke har besøkt".

2018-10-18 11:31 UTC, JorgenJohansen commented on components/Geolocation.js
> +    //Funksjon som lager en oppdatert liste med hva vi har besøkt
Lagt til en bedre forklaring, med hvilke typer vi tar inn og returnerer.

2018-10-18 11:35 UTC, JorgenJohansen commented on components/Geolocation.js
> +import React, {Component} from 'react';
Skrevet en kommentar om hva komponenten gjør og hvem som har skrevet koden.

2018-10-18 11:37 UTC, JorgenJohansen commented on components/Geolocation.js
> +    //Funksjoner som sjekker om vi er i nærheten av målet vårt
Har lagt til en bedre forklaring, samt hvilke typer de er og hvordan de brukes.

2018-10-18 11:39 UTC, JorgenJohansen commented on screens/GeolocationScreen.js
> +    title: 'app.json',
Endret navnet på tittel til Geolocation.

2018-10-18 11:47 UTC, JorgenJohansen commented on components/Geolocation.js
> +    //Funksjon som returnerer distansen mellom to steder
Har tatt med euklidsk distanse og utregning i grader i kommentaren, samt hva argumentene og returnen gjør og hvilke typer de har.

2018-10-18 13:13 UTC, JorgenJohansen commented on components/Geolocation.js
> +        }
Dette skal nå være løst med funksjonen populateMarkers.

2018-10-19 06:50 UTC, S1GGEN requested changes
Veldig bra forbedring, er bare et par småting som må fikses, har prøvd å legge med forslag på hva som kan gjøres på de fleste

2018-10-19 06:50 UTC, S1GGEN commented on components/Geolocation.js
> +const LONGITUDE_DELTA = 0.05;
Vel, nå endte du med width og height som ikke er i bruk da

2018-10-19 06:50 UTC, S1GGEN commented on components/Geolocation.js
> +    //currentPos og goalPos har type floats og inneholder lengde - og breddegrad,
Skilles ikke mellom `float`, `int`, `double`, osv i JS. Disse er bare `number` i js.
![image](https://user-images.githubusercontent.com/12127271/47201362-d736da80-d379-11e8-9620-b35da40bc239.png)

Men `currentPos` og `goalPos` her er jo type `object`: 
![image](https://user-images.githubusercontent.com/12127271/47201416-05b4b580-d37a-11e8-8779-1fcb34907d03.png)

2018-10-19 06:50 UTC, S1GGEN commented on components/Geolocation.js
> +        console.log('checking goal:', goalPos.title);
Kan nok fjerne disse konsoll-loggene

2018-10-19 06:50 UTC, S1GGEN commented on components/Geolocation.js
> +            console.log('Is nearby a goal:', goalPos.title);
Og denne

2018-10-19 06:50 UTC, S1GGEN commented on components/Geolocation.js
> +                console.log('Visited new point!!', goalPos.title);
Og denne

2018-10-19 06:50 UTC, S1GGEN commented on components/Geolocation.js
> +    //pos1 og pos2 har typen floats, og inneholder lengde -og breddegrad som brukes i formelen
Skilles ikke mellom `float`, `int`, `double`, osv i JS. Disse er bare `number` i js.
![image](https://user-images.githubusercontent.com/12127271/47201362-d736da80-d379-11e8-9620-b35da40bc239.png)

Men `pos1` og `pos2` er jo type `object`: 
![image](https://user-images.githubusercontent.com/12127271/47201416-05b4b580-d37a-11e8-8779-1fcb34907d03.png)

2018-10-19 06:50 UTC, S1GGEN commented on components/Geolocation.js
> +    //Funksjon som sjekker om vi er i nærheten av målet vårt
_"om vi er i nærheten av et mål"_ blir vel mer riktig, da denne går igjennom alle mål som enda ikke er besøkt

2018-10-19 06:50 UTC, S1GGEN commented on components/Geolocation.js
> +    //Funksjon som finner posisjonen til bruker ved hjelp av en async callback(anonym funksjon)
Blir litt rart å kalle dette en anonym funksjon, da vi assigner den et navn.

"Asynchronous som etterspør posisjonstillatelse, deretter skaffer posisjon og oppdaterer state. Kaller `callback` når setState er ferdig. Benytter seg av Expo sine Permission og Location" er nok en bedre forklaring

2018-10-19 06:50 UTC, S1GGEN commented on components/Geolocation.js
> +    //Funksjon som kaller getLocationAsync med checkGoals som parameter
Denne er fortsatt ikke fiksa.

"Funksjon som etterspør posisjon med getLocationAsync, og this.checkGoals som callback som blir kalt når getLocationAsync er ferdig." er en mulig kommentar her

2018-10-19 06:50 UTC, S1GGEN commented on components/Geolocation.js
> +    //Vi hindrer at vi får flere markører fra vår posisjon
Denne er fortsatt ikke besvart. Siden vi ikke bruker noen stopWatch lenger (watchPosition var det vel som brukte, men den bruker vi ikke lenger (og vi har ikke noen watchID i state))

2018-10-19 06:50 UTC, S1GGEN commented on screens/GeolocationScreen.js
> +     * content, we just wanted to give you a quick view of your config */
Denne kommentaren kan vel også fjernes

2018-10-19 07:02 UTC, JorgenJohansen commented on components/Geolocation.js
> +const LONGITUDE_DELTA = 0.05;
Dette brukes for høyde og bredde i map som ligger i stylesheeten.

2018-10-19 07:15 UTC, JorgenJohansen commented on components/Geolocation.js
> +        console.log('checking goal:', goalPos.title);
Har kommentert de ut, hvis vi skal bruke dem senere.

2018-10-19 10:28 UTC, S1GGEN requested changes
Ser veldig bra ut nå, men du må huske å faktisk få med deg alle kommentarene jeg legger igjen her

2018-10-19 10:28 UTC, S1GGEN commented on components/Geolocation.js
> +const LONGITUDE_DELTA = 0.05;
Ahh, du har selvfølgelig rett

2018-10-19 10:28 UTC, S1GGEN commented on components/Geolocation.js
> +    //Funksjon tick kjøres når vi rendrer komponenten
componentDidMount-kommentaren er fortsatt ikke utbedret

2018-10-19 10:28 UTC, S1GGEN commented on components/Geolocation.js
> +    //Funksjon tick kjøres når vi rendrer komponenten
Forslag:

Funksjonen `tick` kjøres med en gang komponenten `mountes`, deretter med et interval satt i `TICK_INTERVAL`. Dette gjøres for å kontinuerlig oppdatere posisjonen. Vi ville likt å bruke WatchPosition, men vi fikk den virkelig ikke til å fungere, men dette er noe vi ville likt å få til i en eventuell senere versjon.

2018-10-19 11:13 UTC, S1GGEN submitted a review, later dismissed
Nydelig! :1st_place_medal: :world_map:
Dette er kjempebra, nå gleder jeg meg virkelig til å gå på tur med appen vår!

2018-10-19 11:23 UTC, S1GGEN commented
Her skjedde det en feil, Jørgen skulle ikke ha lukka denne pull requesten

2018-10-19 11:23 UTC, S1GGEN approved these changes

2018-10-19 11:24 UTC, S1GGEN commented
Fiksa merge conflict med develop

2018-10-19 11:24 UTC, merged