#2 Har lagt til Todolist.js, TodolistScreen.js, endret på MainTabNavi…
IT2810/it2810-webutvikling-h18-prosjekt-3-47 pull request #6
Opened 2018-10-02 08:01 UTC by JorgenJohansen

…gator og fikset en warning som var i koden til Todolist.js.

2018-10-02 09:36 UTC, S1GGEN requested changes
Hvis teksten brukeren skriver inn er lengre enn feltet er bredt, vil knappen for å fjerne tasken bli borte. Sannsynligvis en styling-greie som ikke bør være for vanskelig å fikse.

![image](https://user-images.githubusercontent.com/12127271/46340398-99297f00-c635-11e8-8747-5d43029dafa9.png)

Samt er par andre småting som bør fikses/diskuteres.

2018-10-02 09:36 UTC, S1GGEN commented on navigation/MainTabNavigator.js
> +      name={Platform.OS === 'ios' ? `ios-options${focused ? '' : '-outline'}` : 'md-checkbox'}
Kan kanskje prøve å finne et iOS-ikon som passer her

2018-10-02 09:36 UTC, S1GGEN commented on components/Todolist.js
> +const isAndroid = Platform.OS == "android";
Her bør det være **tre** likhetstegn

`Platform.OS === "android";`

2018-10-02 09:36 UTC, S1GGEN commented on components/Todolist.js
> +                <Button title="X" onPress={() => this.deleteTask(index)} />
Hadde det gitt mer mening å ha checkmark her i stedet for `X`?

2018-10-02 09:36 UTC, S1GGEN commented on components/Todolist.js
> +                <Button title="X" onPress={() => this.deleteTask(index)} />
Pros med checkmark:
* Man fullfører en oppgave på todo-lista, føles mer naturlig med checkmark da

Cons med checkmark:
* Ikke alltid man "fullfører" en oppgave på todo-lista, noen ganger bare sletter man en oppgave fordi man bestemte seg for at man ikke gidder å gjøre den

2018-10-02 09:36 UTC, S1GGEN commented on screens/TodolistScreen.js
> +}
Burde være newline på slutten av alle filer

https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

2018-10-02 09:36 UTC, S1GGEN commented on components/Todolist.js
> +AppRegistry.registerComponent("TodoList", () => TodoList);
Burde være newline på slutten av alle filer

https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

2018-10-05 06:50 UTC, JorgenJohansen commented on components/Todolist.js
> +                <Button title="X" onPress={() => this.deleteTask(index)} />
Ser at hvis vi skulle hatt checkmark, må vi endre på måten vi har lagd todolista på, evt. sørge for at bruker kan endre og/eller slette elementet når han/hun trykker på det.

2018-10-05 08:33 UTC, JorgenJohansen commented on navigation/MainTabNavigator.js
> +      name={Platform.OS === 'ios' ? `ios-options${focused ? '' : '-outline'}` : 'md-checkbox'}
Kan prøve task, dog jeg har ikke en iPhone å teste på.

2018-10-05 08:59 UTC, JorgenJohansen commented on navigation/MainTabNavigator.js
> +      name={Platform.OS === 'ios' ? `ios-options${focused ? '' : '-outline'}` : 'md-checkbox'}
Har lagd en ny issue på dette #8.

2018-10-05 09:01 UTC, S1GGEN approved these changes

2018-10-05 09:03 UTC, S1GGEN commented
Ser bra ut nå, bra jobba! :ok_hand: :ok_man: :ok_woman:

2018-10-05 09:03 UTC, merged